### PR TITLE
Make EnergyModelsInvestments independent of EnergyModelsBase

### PR DESCRIPTION
**Pull request by hellemo**
The investment variables and constrains from `EnergyModelsInvestments` (EMI) can be useful also for other models (not necessarily related to energy, e.g. transport, manufacturing). This is an attempt to make EMI independent of `EnergyModelsBase` (EMB).

Note that the tests will only run locally if the following branch of EMB https://github.com/EnergyModelsX/EnergyModelsBase.jl/pull/34 is checked out in the same directory as this branch of EMI.

This PR does the following:

1. Move EMI specific code to an extension in EMI (deleted in this PR, added to EMB in https://github.com/EnergyModelsX/EnergyModelsBase.jl/pull/34 )
2. Make all types defined in EMI independent of EMB, e.g. no longer `abstract type InvestmentData <: EMB.Data end`
3. Disable support for `EnergyModelsGeography` (also tests)
4. Clean up tests a bit (suppress output and pass ENV variable to `dev` EMI for tests)
5. Formatting with `JuliaFormatter`

Things to do:

- [x] Reenable support for `EnergyModelsGeography` (after deciding how to do this)
- [x] Discuss overall approach and improvements
- [ ] Release and register compatible version of EMB before merging
- [ ] Remove temporary code in examples to run with EMB branch
- [x] Update documentation with examples both involving EMB and other model

### CODE REVIEW

**Comment by JulStraus** [comment]
I moved the EMB specific types to the EMB extensions, as shown by commits [Moved EMB specifics to EMB](https://github.com/EnergyModelsX/EnergyModelsBase.jl/pull/34/commits/a153de777ab066d58da8197950a0ee3345eef1ad) and [Moved legacy constructors to EMB extension](https://github.com/EnergyModelsX/EnergyModelsBase.jl/pull/34/commits/4819f94ca0b0226b9cb933edb6609efa9352c045). This includes as well all legacy constructors, except for `TransInvData`.

This has two major implications. Some functions we used previously in the `GeoExt` are now required to be defined in the new extension in `EnergyModelsGeography`, namely `EMI.investment_data(tm::EMG.TransmissionMode)` , `has_investment(tm::EMG.TransmissionMode)`, and `EMI.start_cap(tm::EMG.TransmissionMode, t_inv, inv_data::NoStartInvData, cap)`.

The main reason to redefine them is to allow reference methods in `EnergyModelsInvestments` that provide an error if the function is not specified directly by the user.

**Comment by hellemo** [comment]
I think for maintenance it could be a good idea to move all functions that need to be implemented by a package using `EnergyModelsInvestments` (i.e. `has_investment`, `investment_data`,  and `start_cap`, possibly more later) to a single file and call it `interface.jl` or something related?

**Comment by JulStraus** [comment]
> I think for maintenance it could be a good idea to move all functions that need to be implemented by a package using `EnergyModelsInvestments` (i.e. `has_investment`, `investment_data`, and `start_cap`, possibly more later) to a single file and call it `interface.jl` or something related?

I agree. Of these functions, only `start_cap` has to be defined by the user for `NoStartInvData`. All other functions are used locally in the respective extensions. The other two functions are only necessary for a) the tests to run (`investment_data` on that specific type, that can be easily changed) or in the functions `constraints_capacity_installed` (`has_investment` and `investment_data(n, field)`. In that respect, the functions are EMX specific.

**Comment by hellemo** [comment]
Sure, but other users will probably have similar needs, and when multiple packages (e.g. EMB and EMG) are adding extensions for EMI, these functions needs to belong somewhere, and I think EMI is the natural place.

**Review by JulStraus — APPROVED** [review]
Based on the implemented changes, we have now a version that can be utilized within `EnergyModelsBase`. The changes look in general promising and the documentation was updated to highlight approaches for utilizing `EnergyModelsInvestments`.

The following two bullet points were not included:

- [ ]  Release and register compatible version of EMB before merging
- [ ]  Remove temporary code in examples to run with EMB branch

Point 1 was not included as it seemed best to first register `EnergyModelsInvestments` to avoid a hen and egg problem. To this end, we have to disable the tests in a separate PR for registering `EnergyModelsInvestments`.

Point 2 is difficult for me to understand after the holidays, but I think it was essentially solved by the subsequent changes as we do not have any temporary code in the examples.

Thinks to do before registering the package:

- [x] Separate PR for deactivation of the tests
- [x] Update the version number

**Comment by hellemo** [comment]
Yes, this should be ready now. The issue with temporary code was a workaround using local versions to get around the dependency issues if I remember correctly.

**Pull request merged**
